NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('news.urls')),
]

NewsPortal/news/urls.py
from django.urls import path
from .views import (
   PostsList, PostDetail, SearchPostsList,
   PostCreate, PostUpdate, PostDelete,
   subscriptions,
)


urlpatterns = [
   path('news/', PostsList.as_view(), name='post_list'),
   path('news/<int:id>', PostDetail.as_view(), name='post_detail'),
   path('news/search/', SearchPostsList.as_view(), name='search'),
   path('news/create/', PostCreate.as_view(), name='post_create'),
   path('news/<int:pk>/edit/', PostUpdate.as_view(), name='post_edit'),
   path('news/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('articles/create/', PostCreate.as_view(), name='post_create'),
   path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='post_edit'),
   path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.authorUser.username

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat*3+cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'{self.title}: {self.text[:20]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

NewsPortal/news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post


class PostForm(forms.ModelForm):
    text = forms.CharField(min_length=20)
    class Meta:
        model = Post
        fields = [
            'author',
            'postCategory',
            'title',
            'text',
        ]

    def clean(self):
        cleaned_data = super().clean()
        text = cleaned_data.get("text")
        title = cleaned_data.get("title")
        if title == text:
            raise ValidationError(
                "Текст новости не должен повторять заголовок."
            )
        return cleaned_data

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title[0].islower():
            raise ValidationError(
                "Заголовок должен начинаться с заглавной буквы"
            )
        return title

NewsPortal/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from datetime import datetime
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, DetailView, CreateView,
    UpdateView, DeleteView
)
from .filters import PostFilter
from .forms import PostForm
from .models import Post, Subscriber, Category
from pprint import pprint
from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from .tasks import send_new_post


class PostsList(ListView):
    model = Post
    ordering = '-dateCreation'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        context['next_sale'] = None
        context['filterset'] = self.filterset
        pprint(context)
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'


class SearchPostsList(PostsList):
    template_name = 'search.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs


class PostCreate(LoginRequiredMixin, CreateView):
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'
    context_object_name = 'post'

    def form_valid(self, form):
        current_url = self.request.path
        post = form.save(commit=False)
        if current_url == 'news/create/':
            post.categoryType = 'NW'
        else:
            post.categoryType = 'AR'
        post.save()
        send_new_post.delay(post.pk)
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, UpdateView):
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        current_url = self.request.path
        post = form.save(commit=False)
        if current_url == 'news/<int:pk>/update/':
            post.categoryType = 'NW'
        else:
            post.categoryType = 'AR'
        return super().form_valid(form)


class PostDelete(LoginRequiredMixin, DeleteView):
    raise_exception = True
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscriber.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscriber.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscriber.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )

NewsPortal/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> Здравствуйте! Новые статьи за последнюю неделю!</h2>
<ul>
    {% for post in posts %}
    <li><a href="{{ link }}{{post.get_absolute_url}}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

NewsPortal/templates/news.html
{% extends 'flatpages/default.html' %} 

{% load custom_filters %}!
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    <h3>{{ news|length }}</h3>
    <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}">Добавить новость</a>
    {% endif %}

    {% if news %}
        <table>
            <tr>
                <td>Заголовок новости</td>
                <td>Дата публикации</td>
                <td>Новость</td>
                {% if perms.news.change_post %}
                    <td>Действия</td>
                {% endif %}
            </tr>
            {% for post in news %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.dateCreation }}</td>
                <td>{{ post.text|truncatewords:20|censor }}</td>
                <td>
                    {% if perms.news.change_post %}
                        <a href="{% url 'post_edit' pk=post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                        <a href="{% url 'post_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

NewsPortal/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}!
{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    <h1>{{ post.title|censor }}</h1>
    <tr><h3>{% current_time '%d %b %Y' %}</h3></tr>
    <tr>{{ post.text|censor }}</tr>
{% endblock content %}

NewsPortal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> Новость </h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}!
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <h3>{{ news|length }}</h3>

    <form action="" method="get">
        {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}">Добавить новость</a>
    {% endif %}

    {% if news %}
        <table>
            <tr>
                <td>Заголовок новости</td>
                <td>Дата публикации</td>
                <td>Новость</td>
                {% if perms.news.change_post %}
                    <td>Действия</td>
                {% endif %}
            </tr>
            {% for post in news %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.dateCreation }}</td>
                <td>{{ post.text|truncatewords:20|censor }}</td>
                <td>
                    {% if perms.news.change_post %}
                        <a href="{% url 'post_edit' pk=post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                        <a href="{% url 'post_delete' post.id %}">Удалить</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPortal/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}